### ISSUE TITLE
Дз4 проверенно 

### ISSUE THREAD

**Issue by amozglyakov** [MIEE-ACS/domashnee-zadanie-no4-amozglyakov#1]

**Comment by d-makarenko** [comment]
1. Нет проверки корректности ввода данных от пользователя.

2.  `double max = int.MinValue;` , В конкретно этой ситуации такая строчка работать будет, но в целом это неправильно. int.MinValue содержит минимально допустимое значение для int, а переменная max имеет тип double, и для double минимально допустимое значение другое (гораздо меньше чем для int)
